functionID: id
settings:
  - name: 'Function API key'
    label: 'api key'
    description: 'function API key'
    required: true
    sensitive: true
    type: 'STRING'
displayName: my function
logoUrl: logo.url
resourceType: "DESTINATION"
description: my function description