name: 'Update Segment Functions'
description: 'Updates functions on segment with the source code present in a given repository.'
inputs:
  authorization-token:
    description: 'The authorization token used to access Segment public APIs of your account.'
    required: true
    default: ''
  github-token:
    description: 'A valid Github token to allow the action to have access to all files within a pull request. Please use the secrets.GITHUB_TOKEN.'
    required: true
    default: ''
  pr-number:
    description: 'The number of the current pull request. Please use the github.event.issue.number.'
    required: true
    default: ''
runs:
  using: 'node20'
  main: 'index.js'